"""add lease_expires_at to jobs

Revision ID: 7f02cb860db4
Revises: 87bc0c6256b0
Create Date: 2026-03-05 22:44:56.859546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f02cb860db4'
down_revision: Union[str, Sequence[str], None] = '87bc0c6256b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'lease_expires_at')
    # ### end Alembic commands ###
