"""add indexes for claim reaper and history queries

Revision ID: c6f439a8a545
Revises: 7f02cb860db4
Create Date: 2026-03-06 11:19:43.973036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f439a8a545'
down_revision: Union[str, Sequence[str], None] = '7f02cb860db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_job_events_job_id', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_index('idx_jobs_claim', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('idx_jobs_reaper', 'jobs', ['status', 'lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_reaper', table_name='jobs')
    op.drop_index('idx_jobs_claim', table_name='jobs')
    op.drop_index('idx_job_events_job_id', table_name='job_events')
    # ### end Alembic commands ###
